# 3. Deploy Mail Handler (from the repository root)
- name: 📧 Deploy Mail Handler
  uses: SamKirkland/FTP-Deploy-Action@v4.3.6
  with:
    server: ${{ secrets.FTP_HOST }}
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    local-dir: ./
    server-dir: public_html/
    protocol: ftps
    # 1. EXCLUDE ALL files first
    exclude: "**/*"
    # 2. THEN explicitly INCLUDE the PHP file
    include: "mail_handler.php"
